version: "3.3"

services:
  mynginx:
    image: nginx:latest
    container_name: mynginx
    networks: 
      - mynet
    ports:
      - 8080:80
    volumes:
      - ./src/website:/var/www/html
      - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
    links:
      - myphp:myphp

  myphp:
    build: src/php
    container_name: myphp
    networks: 
      - mynet
    ports: 
      - 9000:9000
    volumes: 
      - ./src/website:/var/www/html
    links:
      - mysql:mysql
  mysql:
    image: mariadb:latest
    container_name: mysql
    networks: 
      - mynet
    volumes:
      - ./src/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: DontUseRootPassword
      MYSQL_DATABASE: yesteryears
      MYSQL_USER: phpservice
      MYSQL_PASSWORD: phpservice

  phpMyAdmin: 
    image: phpmyadmin
    networks: 
      - mynet
    container_name: phpMyAdmin
    ports:
      - 8082:80
    links: 
      - mysql:db
    environment: 
      MYSQL_ROOT_PASSWORD: MyDBRoot123


networks: 
  mynet:
    driver: bridge
  
